services:
  app:
    build:
      context: ./services/api
    environment:
      - DATABASE_URL=postgresql+psycopg2://labuser:labpass@db:5432/labdb
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=labuser
      - POSTGRES_PASSWORD=labpass
      - POSTGRES_DB=labdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labuser -d labdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
